[package]
name = "simplekanainput"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
backend-sfml = ["dep:egui-sfml", "dep:sfml-xt", "dep:arboard"]
backend-eframe = ["dep:eframe"]
ipc = []
default = ["backend-sfml", "ipc"]

[dependencies]
anyhow = "1.0.71"
jmdict = { git = "https://github.com/crumblingstatue/rust-jmdict.git", features = [
    "scope-uncommon",
] }
rfd = "0.11.3"
serde = { version = "1.0.160", features = ["derive"] }
mugo = { git = "https://github.com/crumblingstatue/mugo.git" }
egui_extras = "0.26.2"

# SFML backend
egui-sfml = { git = "https://github.com/crumblingstatue/egui-sfml.git", optional = true }
sfml-xt = { git = "https://github.com/crumblingstatue/sfml-xt.git", optional = true }
arboard = { version = "3.2.0", optional = true }

# eframe backend
eframe = { version = "0.26.2", optional = true }

# Eframe (web)
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"

# Compile deps with optimizations in dev mode
[profile.dev.package."*"]
opt-level = 2
