[package]
name = "simplekanainput"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.2.0"
directories = "4.0.1"
egui-sfml = "0.4.0"
jmdict = "2.0.0"
open = "3.2.0"
rfd = "0.11.1"
serde = { version = "1.0.152", features = ["derive"] }
