[package]
name = "simplekanainput"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
arboard = "3.2.0"
egui-sfml = "0.4.0"
jmdict = "2.0.0"
rfd = "0.11.3"
serde = { version = "1.0.160", features = ["derive"] }
