[package]
name = "simplekanainput"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
arboard = "3.2.0"
egui-sfml = { git = "https://github.com/crumblingstatue/egui-sfml.git" }
sfml-xt = { git = "https://github.com/crumblingstatue/sfml-xt.git" }
jmdict =  { git = "https://github.com/crumblingstatue/rust-jmdict.git", features = ["scope-uncommon"] }
rfd = "0.11.3"
serde = { version = "1.0.160", features = ["derive"] }
mugo = { git = "https://github.com/crumblingstatue/mugo.git" }
egui_extras = "0.26.2"

# Compile deps with optimizations in dev mode
[profile.dev.package."*"]
opt-level = 2
