struct RomajiKanaPair {
    romaji: &'static str,
    kana: &'static str,
}

pub struct RomajiKanaTable {
    table: &'static [RomajiKanaPair],
}

impl RomajiKanaTable {
    pub fn lookup(&self, romaji: &str) -> Option<&'static str> {
        self.table
            .iter()
            .find_map(|pair| (pair.romaji == romaji).then_some(pair.kana))
    }
}

macro_rules! kana_table {
    ($id:ident $($romaji:literal $kana:literal)+) => {
        pub static $id: RomajiKanaTable = RomajiKanaTable { table: &[
                $(
                RomajiKanaPair {
                        romaji: $romaji,
                        kana: $kana
                },
                )+
            ]
        };
    };
}

kana_table! {
    HIRAGANA
    "a" "あ"
    "_a" "ぁ"
    "i" "い"
    "u" "う"
    "e" "え"
    "o" "お"
    "ka" "か"
    "ki" "き"
    "kyu" "きゅ"
    "kyo" "きょ"
    "kya" "きゃ"
    "ku" "く"
    "ke" "け"
    "kke" "っけ"
    "kka" "っか"
    "kku" "っく"
    "kki" "っき"
    "ko" "こ"
    "kko" "っこ"
    "ga" "が"
    "gi" "ぎ"
    "gya" "ぎゃ"
    "gyo" "ぎょ"
    "gu" "ぐ"
    "ge" "げ"
    "go" "ご"
    "ra" "ら"
    "ri" "り"
    "rya" "りゃ"
    "ryo" "りょ"
    "ryu" "りゅ"
    "ru" "る"
    "re" "れ"
    "ro" "ろ"
    "sa" "さ"
    "za" "ざ"
    "sshi" "っし"
    "shi" "し"
    "sha" "しゃ"
    "sho" "しょ"
    "shu" "しゅ"
    "ji" "じ"
    "ju" "じゅ"
    "jo" "じょ"
    "ja" "じゃ"
    "su" "す"
    "zu" "ず"
    "se" "せ"
    "ze" "ぜ"
    "so" "そ"
    "zo" "ぞ"
    "ta" "た"
    "tta" "った"
    "da" "だ"
    "chi" "ち"
    "cha" "ちゃ"
    "cho" "ちょ"
    "chu" "ちゅ"
    "di" "ぢ"
    "tsu" "つ"
    "du" "づ"
    "te" "て"
    "tte" "って"
    "de" "で"
    "to" "と"
    "tto" "っと"
    "do" "ど"
    "na" "な"
    "ni" "に"
    "nya" "にゃ"
    "nyo" "にょ"
    "nyu" "にょ"
    "nu" "ぬ"
    "ne" "ね"
    "no" "の"
    "ha" "は"
    "ba" "ば"
    "pa" "ぱ"
    "hi" "ひ"
    "hya" "ひゃ"
    "bi" "び"
    "pi" "ぴ"
    "fu" "ふ"
    "bu" "ぶ"
    "pu" "ぷ"
    "he" "へ"
    "be" "べ"
    "pe" "ぺ"
    "ho" "ほ"
    "bo" "ぼ"
    "po" "ぽ"
    "ma" "ま"
    "mi" "み"
    "mu" "む"
    "me" "め"
    "mo" "も"
    "ya" "や"
    "yu" "ゆ"
    "yo" "よ"
    "wa" "わ"
    "wo" "を"
    "nn" "ん"
    "-"  "ー"
    "."  "。"
    ","  "、"
    "!"  "！"
}

kana_table! {
    KATAKANA
    "a" "ア"
    "i" "イ"
    "u" "ウ"
    "e" "エ"
    "o" "オ"
    "ka" "カ"
    "ga" "ガ"
    "ki" "キ"
    "kyu" "キュ"
    "kyo" "キョ"
    "kya" "キャ"
    "gi" "ギ"
    "gya" "ギャ"
    "ku" "ク"
    "kku" "ック"
    "kki" "ッキ"
    "gu" "グ"
    "ke" "ケ"
    "ge" "ゲ"
    "ko" "コ"
    "go" "ゴ"
    "sa" "サ"
    "za" "ザ"
    "shi" "シ"
    "sshi" "ッシ"
    "sha" "シャ"
    "sho" "ショ"
    "shu" "シュ"
    "ji" "ジ"
    "ju" "ジュ"
    "ja" "ジャ"
    "jo" "ジョ"
    "su" "ス"
    "zu" "ズ"
    "se" "セ"
    "ze" "ゼ"
    "so" "ソ"
    "zo" "ゾ"
    "ta" "タ"
    "da" "ダ"
    "chi" "チ"
    "cha" "チャ"
    "cho" "チョ"
    "chu" "チュ"
    "di" "ヂ"
    "tsu" "ツ"
    "du" "ヅ"
    "te" "テ"
    "de" "デ"
    "to" "ト"
    "do" "ド"
    "na" "ナ"
    "ni" "ニ"
    "nya" "ニャ"
    "nyo" "ニョ"
    "nyu" "ニュ"
    "nu" "ヌ"
    "ne" "ネ"
    "no" "ノ"
    "ha" "ハ"
    "ba" "バ"
    "pa" "パ"
    "hi" "ヒ"
    "hya" "ヒャ"
    "bi" "ビ"
    "pi" "ピ"
    "fu" "フ"
    "bu" "ブ"
    "pu" "プ"
    "he" "ヘ"
    "be" "ベ"
    "pe" "ペ"
    "ho" "ホ"
    "bo" "ボ"
    "po" "ポ"
    "ma" "マ"
    "mi" "ミ"
    "mu" "ム"
    "me" "メ"
    "mo" "モ"
    "ya" "ヤ"
    "yu" "ユ"
    "yo" "ヨ"
    "ra" "ラ"
    "ri" "リ"
    "rya" "リャ"
    "ryo" "リョ"
    "ryu" "リュ"
    "ru" "ル"
    "re" "レ"
    "ro" "ロ"
    "wa" "ワ"
    "wo" "ヲ"
    "nn" "ン"
    "-"  "ー"
    "."  "。"
    ","  "、"
    "!"  "！"
}

// ぃぅぇぉゃゅゎゕゖ゛゜ゝゞゟ ゔ
// ゐ = wi (obsolete kana)
// ゑ = we (obsolete kana)

// ッィゥェォャュョヰヱヴヵヶヷヸヹヺ・ーヽヾヮ
